version: 0.2

phases:
  install:
    runtime-version:
      docker: 19

  pre_build:
    commands:
      - ECR_URI=386197392083.dkr.ecr.us-east-1.amazonaws.com
      - IMAGE_NAME="webapp"
      - echo Installing ECS Tools...
      - dotnet tool install -g Amazon.ECS.Tools
      
  build:
    commands:
      - echo Build started on `date`
      - cd ./aspnet-demo-1
      - dotnet ecs push-image $REPOSITORY_URI --tag $|IMAGE_NAME
      
  post_build:
    commands:
      - echo writing image definitions file...
      - printf '[{"name:":"webapp-container", "imageUri":"%s}]' $ECR_URI/$IMAGE_NAME > imagedefinitions.json

  artifacts:
    file: ././aspnet-demo-1/imagedefinitions.json
    discard-discard-path: yes