# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  minimalwebapi:
    image: minimal-web-api:v1
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5000:5000
